# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Orchestrate or schedule a set of jobs
workflows:
  # Name the workflow "welcome"
  welcome:
    # Run the welcome/run job in its own container
    jobs:
      - MyTestBuildStep

executors:
  dockerexectest:
    docker:
      - image: debian:stretch
  vmmachine:
    machine:
       image: ubuntu-2004:202010-01


commands:
  setupmachine:
    steps: 
        - run: sudo apt update 
        - run: sudo apt install build-essential


jobs:
  MyTestBuildStep:
    executor: vmmachine
    steps:
      - checkout
      - setupmachine
      #- run:
        #  name: setupMachine 
       #   command: sudo apt update
      #- run:
          #command: sudo apt install build-essential
      - run:
          name: compile
          command: g++ -o main main.cpp

      - run:
          name: run it
          command: ./main